# Site settings
name: Yuan He
title: Yuan He | Full-Stack Developer
description: a full-stack developer & a blockchain nubee
url: https://yuanhe.fun/
baseurl: ""
email: yh772@cornell.edu
cover: https://brittanychiang.com/img/og.png
logo: https://brittanychiang.com/img/emojis/technologist.png
resume: https://yuanhe.fun/resume.pdf
social:
  - title: email
    url: mailto:yh772@cornell.edu
  - title: github
    url: https://github.com/yuanhe772
  - title: linkedin
    url: https://www.linkedin.com/in/yuanhe772

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
